import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const pluginDir = '.obsidian/plugins/project-manager';
const manifestPath = 'manifest.json';

// 确保插件目录存在
function ensurePluginDir() {
  const fullPath = path.join(process.cwd(), pluginDir);
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true });
    console.log(`📁 创建插件目录: ${pluginDir}`);
  }
}

// 复制文件到插件目录
function copyToPluginDir(filename) {
  const srcPath = path.join(process.cwd(), filename);
  const destPath = path.join(process.cwd(), pluginDir, filename);

  if (fs.existsSync(srcPath)) {
    fs.copyFileSync(srcPath, destPath);
    return true;
  }
  return false;
}

// 写入 .hotreload 文件触发 Obsidian 重载
function triggerHotReload() {
  const hotreloadPath = path.join(process.cwd(), pluginDir, '.hotreload');
  fs.writeFileSync(hotreloadPath, '');
}

// 显示构建结果统计
function showBuildStats(result) {
  if (result.metafile) {
    const outputs = Object.entries(result.metafile.outputs);
    outputs.forEach(([file, info]) => {
      if (file.endsWith('.js')) {
        const sizeKB = (info.bytes / 1024).toFixed(1);
        console.log(`📦 ${file}: ${sizeKB} KB`);
      }
    });
  }
}

// 打印带颜色的日志
function log(type, message) {
  const colors = {
    info: '\x1b[36m',    // 青色
    success: '\x1b[32m', // 绿色
    error: '\x1b[31m',   // 红色
    warning: '\x1b[33m', // 黄色
    reset: '\x1b[0m'
  };
  console.log(`${colors[type] || colors.info}${message}${colors.reset}`);
}

// 自定义插件：构建完成后复制文件
const hotReloadPlugin = {
  name: 'hot-reload',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) {
        log('error', '❌ 构建失败:');
        result.errors.forEach(err => console.error(err));
        return;
      }

      console.log('\n' + '='.repeat(50));
      log('info', '🔄 检测到文件变化，重新构建...');

      // 复制文件
      let updatedFiles = [];
      if (copyToPluginDir('main.js')) updatedFiles.push('main.js');
      if (copyToPluginDir('styles.css')) updatedFiles.push('styles.css');

      // 触发重载
      triggerHotReload();

      log('success', '✅ 构建成功！');
      console.log(`📋 已更新: ${updatedFiles.join(', ')}`);
      showBuildStats(result);
      console.log('='.repeat(50) + '\n');
    });
  }
};

console.log('🔥 启动热重载开发模式...\n');

// 确保插件目录存在
ensurePluginDir();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/*',
    'lezer',
    ...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: "silent",
  sourcemap: 'inline',
  treeShaking: true,
  metafile: true,
  outfile: 'main.js',
  plugins: [hotReloadPlugin],
});

// 首次构建
console.log('⏳ 首次构建中...');
const initialResult = await context.rebuild();

if (initialResult.errors.length > 0) {
  log('error', '❌ 首次构建失败:');
  initialResult.errors.forEach(err => console.error(err));
  process.exit(1);
}

// 复制文件
let copiedFiles = [];
if (copyToPluginDir('main.js')) copiedFiles.push('main.js');
if (copyToPluginDir('styles.css')) copiedFiles.push('styles.css');
if (copyToPluginDir(manifestPath)) copiedFiles.push(manifestPath);

// 触发重载
triggerHotReload();

log('success', '✅ 首次构建成功！');
console.log(`📋 已复制: ${copiedFiles.join(', ')}`);
showBuildStats(initialResult);
console.log('\n👀 监听文件变化中...\n');

// 启动 watch 模式
await context.watch();

// 处理退出
process.on('SIGINT', async () => {
  log('info', '\n👋 正在关闭开发服务器...');
  await context.dispose();
  process.exit(0);
});
