/**
 * 模板模块导出
 */

export {
  DEFAULT_TEMPLATES,
  DEFAULT_OVERVIEW_TEMPLATE,
  DEFAULT_VERSION_TEMPLATE,
  DEFAULT_PROJECT_TEMPLATE,
  DEFAULT_FEATURE_TEMPLATE,
  PRIORITY_EMOJI,
  STATUS_EMOJI,
} from './defaults';
